CREATE TABLE IF NOT EXISTS "users" (
	-- ID
	"id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- 名前
	"name" VARCHAR(255) NOT NULL,
	-- メールアドレス
	"email" VARCHAR(255) NOT NULL UNIQUE,
	-- パスワード
	"password" VARCHAR(255) NOT NULL,
	-- メール認証日時
	"email_verified_at" TIMESTAMP,
	-- ログイン保持トークン
	"remember_token" VARCHAR(100),
	-- 作成日時
	"created_at" TIMESTAMP,
	-- 更新日時
	"updated_at" TIMESTAMP,
	PRIMARY KEY("id")
);

COMMENT ON COLUMN "users"."id" IS 'ID';
COMMENT ON COLUMN "users"."name" IS '名前';
COMMENT ON COLUMN "users"."email" IS 'メールアドレス';
COMMENT ON COLUMN "users"."password" IS 'パスワード';
COMMENT ON COLUMN "users"."email_verified_at" IS 'メール認証日時';
COMMENT ON COLUMN "users"."remember_token" IS 'ログイン保持トークン';
COMMENT ON COLUMN "users"."created_at" IS '作成日時';
COMMENT ON COLUMN "users"."updated_at" IS '更新日時';

CREATE TABLE IF NOT EXISTS "streaming_services" (
	-- ID
	"id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- 配信名
	"name" VARCHAR(255) NOT NULL,
	-- ロゴ画像
	"logo_image_url" VARCHAR(512),
	-- TMDBのID
	"tmdb_provider_id" INTEGER NOT NULL UNIQUE,
	-- サービス遷移先URL
	"service_url" VARCHAR(512) NOT NULL,
	-- 作成日時
	"created_at" TIMESTAMP,
	-- 更新日時
	"updated_at" TIMESTAMP,
	PRIMARY KEY("id")
);

COMMENT ON COLUMN "streaming_services"."id" IS 'ID';
COMMENT ON COLUMN "streaming_services"."name" IS '配信名';
COMMENT ON COLUMN "streaming_services"."logo_image_url" IS 'ロゴ画像';
COMMENT ON COLUMN "streaming_services"."tmdb_provider_id" IS 'TMDBのID';
COMMENT ON COLUMN "streaming_services"."service_url" IS 'サービス遷移先URL';
COMMENT ON COLUMN "streaming_services"."created_at" IS '作成日時';
COMMENT ON COLUMN "streaming_services"."updated_at" IS '更新日時';

CREATE TABLE IF NOT EXISTS "anime_titles" (
	-- ID
	"id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- TMDBのID
	"tmdb_id" INTEGER NOT NULL UNIQUE,
	-- 作品名
	"title" VARCHAR(255) NOT NULL,
	-- ポスター画像
	"poster_image_url" VARCHAR(512),
	-- あらすじ
	"synopsis" TEXT,
	-- 最終更新日
	"last_synced_at" TIMESTAMP NOT NULL,
	-- 人気度
	"popularity" NUMERIC(10,3) NOT NULL,
	-- 作成日時
	"created_at" TIMESTAMP,
	-- 更新日時
	"updated_at" TIMESTAMP,
	PRIMARY KEY("id")
);

COMMENT ON COLUMN "anime_titles"."id" IS 'ID';
COMMENT ON COLUMN "anime_titles"."tmdb_id" IS 'TMDBのID';
COMMENT ON COLUMN "anime_titles"."title" IS '作品名';
COMMENT ON COLUMN "anime_titles"."poster_image_url" IS 'ポスター画像';
COMMENT ON COLUMN "anime_titles"."synopsis" IS 'あらすじ';
COMMENT ON COLUMN "anime_titles"."last_synced_at" IS '最終更新日';
COMMENT ON COLUMN "anime_titles"."popularity" IS '人気度';
COMMENT ON COLUMN "anime_titles"."created_at" IS '作成日時';
COMMENT ON COLUMN "anime_titles"."updated_at" IS '更新日時';

CREATE TABLE IF NOT EXISTS "user_subscriptions" (
	-- ID
	"id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- ユーザーID
	"user_id" BIGINT NOT NULL,
	-- 配信サービスID
	"streaming_service_id" BIGINT NOT NULL,
	-- 料金
	"price" INTEGER NOT NULL,
	-- 作成日時
	"created_at" TIMESTAMP,
	-- 更新日時
	"updated_at" TIMESTAMP,
	PRIMARY KEY("id"),
	CONSTRAINT "user_subscriptions_unique_0" UNIQUE ("user_id", "streaming_service_id")
);

COMMENT ON COLUMN "user_subscriptions"."id" IS 'ID';
COMMENT ON COLUMN "user_subscriptions"."user_id" IS 'ユーザーID';
COMMENT ON COLUMN "user_subscriptions"."streaming_service_id" IS '配信サービスID';
COMMENT ON COLUMN "user_subscriptions"."price" IS '料金';
COMMENT ON COLUMN "user_subscriptions"."created_at" IS '作成日時';
COMMENT ON COLUMN "user_subscriptions"."updated_at" IS '更新日時';

CREATE TABLE IF NOT EXISTS "anime_availabilities" (
	-- ID
	"id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- アニメ作品ID
	"anime_title_id" BIGINT NOT NULL,
	-- 配信サービスID
	"streaming_service_id" BIGINT NOT NULL,
	-- 配信状況
	"availability_status" VARCHAR(50) NOT NULL,
	-- 作成日時
	"created_at" TIMESTAMP,
	-- 更新日時
	"updated_at" TIMESTAMP,
	PRIMARY KEY("id"),
	CONSTRAINT "anime_availabilities_unique_0" UNIQUE ("anime_title_id", "streaming_service_id", "availability_status")
);

COMMENT ON COLUMN "anime_availabilities"."id" IS 'ID';
COMMENT ON COLUMN "anime_availabilities"."anime_title_id" IS 'アニメ作品ID';
COMMENT ON COLUMN "anime_availabilities"."streaming_service_id" IS '配信サービスID';
COMMENT ON COLUMN "anime_availabilities"."availability_status" IS '配信状況';
COMMENT ON COLUMN "anime_availabilities"."created_at" IS '作成日時';
COMMENT ON COLUMN "anime_availabilities"."updated_at" IS '更新日時';

CREATE TABLE IF NOT EXISTS "user_anime_lists" (
	-- ID
	"id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- ユーザーID
	"user_id" BIGINT NOT NULL,
	-- アニメ作品ID
	"anime_title_id" BIGINT NOT NULL,
	-- ステータス
	"status" VARCHAR(50) NOT NULL,
	-- 優先度
	"priority" INTEGER,
	-- 作成日時
	"created_at" TIMESTAMP,
	-- 更新日時
	"updated_at" TIMESTAMP,
	PRIMARY KEY("id"),
	CONSTRAINT "user_anime_lists_unique_0" UNIQUE ("user_id", "anime_title_id")
);

COMMENT ON COLUMN "user_anime_lists"."id" IS 'ID';
COMMENT ON COLUMN "user_anime_lists"."user_id" IS 'ユーザーID';
COMMENT ON COLUMN "user_anime_lists"."anime_title_id" IS 'アニメ作品ID';
COMMENT ON COLUMN "user_anime_lists"."status" IS 'ステータス';
COMMENT ON COLUMN "user_anime_lists"."priority" IS '優先度';
COMMENT ON COLUMN "user_anime_lists"."created_at" IS '作成日時';
COMMENT ON COLUMN "user_anime_lists"."updated_at" IS '更新日時';

ALTER TABLE "user_subscriptions"
ADD FOREIGN KEY("user_id") REFERENCES "users"("id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "user_subscriptions"
ADD FOREIGN KEY("streaming_service_id") REFERENCES "streaming_services"("id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "user_anime_lists"
ADD FOREIGN KEY("user_id") REFERENCES "users"("id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "user_anime_lists"
ADD FOREIGN KEY("anime_title_id") REFERENCES "anime_titles"("id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "anime_availabilities"
ADD FOREIGN KEY("streaming_service_id") REFERENCES "streaming_services"("id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "anime_availabilities"
ADD FOREIGN KEY("anime_title_id") REFERENCES "anime_titles"("id")
ON UPDATE NO ACTION ON DELETE RESTRICT;